// Code generated by opphav-gen-symbols. DO NOT EDIT.

package sensors

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "sensors"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// BELOW indicates the measured value is below the setpoint reference.
	BELOW = signs.Define("BELOW")

	// NOMINAL indicates the measured value is at or near the setpoint reference.
	NOMINAL = signs.Define("NOMINAL")

	// ABOVE indicates the measured value is above the setpoint reference.
	ABOVE = signs.Define("ABOVE")
)

var (
	// BASELINE The baseline setpoint represents normal or expected operating level.
	BASELINE = dimensions.Define("BASELINE")

	// THRESHOLD The threshold setpoint represents a limit or boundary that should not be exceeded.
	THRESHOLD = dimensions.Define("THRESHOLD")

	// TARGET The target setpoint represents an ideal or optimal operating point.
	TARGET = dimensions.Define("TARGET")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}
}

// Below returns the BELOW signal for the given dimension.
// Indicates the measured value is below the setpoint reference.
func Below(d Dimension) Signal {
	return signalMap[BELOW][d].(Signal)
}

// Nominal returns the NOMINAL signal for the given dimension.
// Indicates the measured value is at or near the setpoint reference.
func Nominal(d Dimension) Signal {
	return signalMap[NOMINAL][d].(Signal)
}

// Above returns the ABOVE signal for the given dimension.
// Indicates the measured value is above the setpoint reference.
func Above(d Dimension) Signal {
	return signalMap[ABOVE][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

type Sensor struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Sensor {
	if percept == nil {
		panic("sensors: percept must not be nil")
	}

	return &Sensor{percept: percept, subject: subject}
}

// Below emits the BELOW signal.
// Indicates the measured value is below the setpoint reference.
func (i *Sensor) Below(d Dimension) {
	i.percept.Emit(i.subject, signalMap[BELOW][d])
}

// Nominal emits the NOMINAL signal.
// Indicates the measured value is at or near the setpoint reference.
func (i *Sensor) Nominal(d Dimension) {
	i.percept.Emit(i.subject, signalMap[NOMINAL][d])
}

// Above emits the ABOVE signal.
// Indicates the measured value is above the setpoint reference.
func (i *Sensor) Above(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ABOVE][d])
}
