// Code generated by opphav-gen-symbols. DO NOT EDIT.

package outcomes

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "outcomes"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// SUCCESS indicates the operation succeeded.
	SUCCESS = signs.Define("SUCCESS")

	// FAIL indicates the operation failed.
	FAIL = signs.Define("FAIL")

	// UNKNOWN indicates the verdict is indeterminate — neither a clean success nor a definite failure. The
	UNKNOWN = signs.Define("UNKNOWN")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Outcome struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Outcome {
	if percept == nil {
		panic("outcomes: percept must not be nil")
	}

	return &Outcome{percept: percept, subject: subject}
}

// Success emits the SUCCESS sign.
// Indicates the operation succeeded.
func (i *Outcome) Success() {
	i.percept.Emit(i.subject, signMap[SUCCESS])
}

// Fail emits the FAIL sign.
// Indicates the operation failed.
func (i *Outcome) Fail() {
	i.percept.Emit(i.subject, signMap[FAIL])
}

// Unknown emits the UNKNOWN sign.
// Indicates the verdict is indeterminate — neither a clean success nor a definite failure. The
func (i *Outcome) Unknown() {
	i.percept.Emit(i.subject, signMap[UNKNOWN])
}
