// Code generated by opphav-gen-symbols. DO NOT EDIT.

package services

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "services"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// START indicates the start of work execution.
	START = signs.Define("START")

	// STOP indicates the completion of work execution (regardless of outcome).
	STOP = signs.Define("STOP")

	// CALL indicates a request (call) for work to be done by another service.
	CALL = signs.Define("CALL")

	// SUCCESS indicates successful completion of work.
	SUCCESS = signs.Define("SUCCESS")

	// FAIL indicates failure to complete work.
	FAIL = signs.Define("FAIL")

	// RECOURSE indicates activation of a degraded operational mode after failure.
	RECOURSE = signs.Define("RECOURSE")

	// REDIRECT indicates forwarding of work to an alternative service or endpoint.
	REDIRECT = signs.Define("REDIRECT")

	// EXPIRE indicates work exceeded its time budget.
	EXPIRE = signs.Define("EXPIRE")

	// RETRY indicates automatic retry of work after failure.
	RETRY = signs.Define("RETRY")

	// REJECT indicates refusal to accept work.
	REJECT = signs.Define("REJECT")

	// DISCARD indicates deliberate dropping of work.
	DISCARD = signs.Define("DISCARD")

	// DELAY indicates postponement of work.
	DELAY = signs.Define("DELAY")

	// SCHEDULE indicates work queued for future execution.
	SCHEDULE = signs.Define("SCHEDULE")

	// SUSPEND indicates work paused awaiting resumption.
	SUSPEND = signs.Define("SUSPEND")

	// RESUME indicates previously suspended work restarting.
	RESUME = signs.Define("RESUME")

	// DISCONNECT indicates inability to reach or communicate with a service.
	DISCONNECT = signs.Define("DISCONNECT")
)

var (
	// CALLER Signals emitted by the service in the caller role (initiating requests).
	CALLER = dimensions.Define("CALLER")

	// CALLEE Signals emitted by the service in the callee role (serving requests).
	CALLEE = dimensions.Define("CALLEE")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		START:      opphav.KindOperation,
		STOP:       opphav.KindOperation,
		CALL:       opphav.KindOperation,
		SUCCESS:    opphav.KindOutcome,
		FAIL:       opphav.KindOutcome,
		RECOURSE:   opphav.KindOperation,
		REDIRECT:   opphav.KindOperation,
		EXPIRE:     opphav.KindOutcome,
		RETRY:      opphav.KindOperation,
		REJECT:     opphav.KindOutcome,
		DISCARD:    opphav.KindOperation,
		DELAY:      opphav.KindOperation,
		SCHEDULE:   opphav.KindOperation,
		SUSPEND:    opphav.KindOperation,
		RESUME:     opphav.KindOperation,
		DISCONNECT: opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Start returns the START signal for the given dimension.
// Indicates the start of work execution.
func Start(d Dimension) Signal {
	return signalMap[START][d].(Signal)
}

// Stop returns the STOP signal for the given dimension.
// Indicates the completion of work execution (regardless of outcome).
func Stop(d Dimension) Signal {
	return signalMap[STOP][d].(Signal)
}

// Call returns the CALL signal for the given dimension.
// Indicates a request (call) for work to be done by another service.
func Call(d Dimension) Signal {
	return signalMap[CALL][d].(Signal)
}

// Success returns the SUCCESS signal for the given dimension.
// Indicates successful completion of work.
func Success(d Dimension) Signal {
	return signalMap[SUCCESS][d].(Signal)
}

// Fail returns the FAIL signal for the given dimension.
// Indicates failure to complete work.
func Fail(d Dimension) Signal {
	return signalMap[FAIL][d].(Signal)
}

// Recourse returns the RECOURSE signal for the given dimension.
// Indicates activation of a degraded operational mode after failure.
func Recourse(d Dimension) Signal {
	return signalMap[RECOURSE][d].(Signal)
}

// Redirect returns the REDIRECT signal for the given dimension.
// Indicates forwarding of work to an alternative service or endpoint.
func Redirect(d Dimension) Signal {
	return signalMap[REDIRECT][d].(Signal)
}

// Expire returns the EXPIRE signal for the given dimension.
// Indicates work exceeded its time budget.
func Expire(d Dimension) Signal {
	return signalMap[EXPIRE][d].(Signal)
}

// Retry returns the RETRY signal for the given dimension.
// Indicates automatic retry of work after failure.
func Retry(d Dimension) Signal {
	return signalMap[RETRY][d].(Signal)
}

// Reject returns the REJECT signal for the given dimension.
// Indicates refusal to accept work.
func Reject(d Dimension) Signal {
	return signalMap[REJECT][d].(Signal)
}

// Discard returns the DISCARD signal for the given dimension.
// Indicates deliberate dropping of work.
func Discard(d Dimension) Signal {
	return signalMap[DISCARD][d].(Signal)
}

// Delay returns the DELAY signal for the given dimension.
// Indicates postponement of work.
func Delay(d Dimension) Signal {
	return signalMap[DELAY][d].(Signal)
}

// Schedule returns the SCHEDULE signal for the given dimension.
// Indicates work queued for future execution.
func Schedule(d Dimension) Signal {
	return signalMap[SCHEDULE][d].(Signal)
}

// Suspend returns the SUSPEND signal for the given dimension.
// Indicates work paused awaiting resumption.
func Suspend(d Dimension) Signal {
	return signalMap[SUSPEND][d].(Signal)
}

// Resume returns the RESUME signal for the given dimension.
// Indicates previously suspended work restarting.
func Resume(d Dimension) Signal {
	return signalMap[RESUME][d].(Signal)
}

// Disconnect returns the DISCONNECT signal for the given dimension.
// Indicates inability to reach or communicate with a service.
func Disconnect(d Dimension) Signal {
	return signalMap[DISCONNECT][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Service struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Service {
	if percept == nil {
		panic("services: percept must not be nil")
	}

	return &Service{percept: percept, subject: subject}
}

// Start emits the START signal.
// Indicates the start of work execution.
func (i *Service) Start(d Dimension) {
	i.percept.Emit(i.subject, signalMap[START][d])
}

// Stop emits the STOP signal.
// Indicates the completion of work execution (regardless of outcome).
func (i *Service) Stop(d Dimension) {
	i.percept.Emit(i.subject, signalMap[STOP][d])
}

// Call emits the CALL signal.
// Indicates a request (call) for work to be done by another service.
func (i *Service) Call(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CALL][d])
}

// Success emits the SUCCESS signal.
// Indicates successful completion of work.
func (i *Service) Success(d Dimension) {
	i.percept.Emit(i.subject, signalMap[SUCCESS][d])
}

// Fail emits the FAIL signal.
// Indicates failure to complete work.
func (i *Service) Fail(d Dimension) {
	i.percept.Emit(i.subject, signalMap[FAIL][d])
}

// Recourse emits the RECOURSE signal.
// Indicates activation of a degraded operational mode after failure.
func (i *Service) Recourse(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RECOURSE][d])
}

// Redirect emits the REDIRECT signal.
// Indicates forwarding of work to an alternative service or endpoint.
func (i *Service) Redirect(d Dimension) {
	i.percept.Emit(i.subject, signalMap[REDIRECT][d])
}

// Expire emits the EXPIRE signal.
// Indicates work exceeded its time budget.
func (i *Service) Expire(d Dimension) {
	i.percept.Emit(i.subject, signalMap[EXPIRE][d])
}

// Retry emits the RETRY signal.
// Indicates automatic retry of work after failure.
func (i *Service) Retry(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RETRY][d])
}

// Reject emits the REJECT signal.
// Indicates refusal to accept work.
func (i *Service) Reject(d Dimension) {
	i.percept.Emit(i.subject, signalMap[REJECT][d])
}

// Discard emits the DISCARD signal.
// Indicates deliberate dropping of work.
func (i *Service) Discard(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DISCARD][d])
}

// Delay emits the DELAY signal.
// Indicates postponement of work.
func (i *Service) Delay(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DELAY][d])
}

// Schedule emits the SCHEDULE signal.
// Indicates work queued for future execution.
func (i *Service) Schedule(d Dimension) {
	i.percept.Emit(i.subject, signalMap[SCHEDULE][d])
}

// Suspend emits the SUSPEND signal.
// Indicates work paused awaiting resumption.
func (i *Service) Suspend(d Dimension) {
	i.percept.Emit(i.subject, signalMap[SUSPEND][d])
}

// Resume emits the RESUME signal.
// Indicates previously suspended work restarting.
func (i *Service) Resume(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RESUME][d])
}

// Disconnect emits the DISCONNECT signal.
// Indicates inability to reach or communicate with a service.
func (i *Service) Disconnect(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DISCONNECT][d])
}
