// Code generated by opphav-gen-symbols. DO NOT EDIT.

package actors

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "actors"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// ASK Seeking information, clarification, or guidance.
	ASK = signs.Define("ASK")

	// AFFIRM Making a claim or judgment with confidence.
	AFFIRM = signs.Define("AFFIRM")

	// EXPLAIN Providing reasoning, elaboration, or rationale.
	EXPLAIN = signs.Define("EXPLAIN")

	// REPORT Conveying factual observations or findings.
	REPORT = signs.Define("REPORT")

	// REQUEST Asking another actor to perform action at peer level.
	REQUEST = signs.Define("REQUEST")

	// COMMAND Directing another actor to act with authority.
	COMMAND = signs.Define("COMMAND")

	// ACKNOWLEDGE Confirming receipt, understanding, or agreement.
	ACKNOWLEDGE = signs.Define("ACKNOWLEDGE")

	// DENY Disagreeing with or correcting a proposition.
	DENY = signs.Define("DENY")

	// CLARIFY Refining, specifying, or disambiguating intent.
	CLARIFY = signs.Define("CLARIFY")

	// PROMISE Committing to perform future action or deliver work.
	PROMISE = signs.Define("PROMISE")

	// DELIVER Presenting completed work or fulfilled commitment.
	DELIVER = signs.Define("DELIVER")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Actor struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Actor {
	if percept == nil {
		panic("actors: percept must not be nil")
	}

	return &Actor{percept: percept, subject: subject}
}

// Ask emits the ASK sign.
// Seeking information, clarification, or guidance.
func (i *Actor) Ask() {
	i.percept.Emit(i.subject, signMap[ASK])
}

// Affirm emits the AFFIRM sign.
// Making a claim or judgment with confidence.
func (i *Actor) Affirm() {
	i.percept.Emit(i.subject, signMap[AFFIRM])
}

// Explain emits the EXPLAIN sign.
// Providing reasoning, elaboration, or rationale.
func (i *Actor) Explain() {
	i.percept.Emit(i.subject, signMap[EXPLAIN])
}

// Report emits the REPORT sign.
// Conveying factual observations or findings.
func (i *Actor) Report() {
	i.percept.Emit(i.subject, signMap[REPORT])
}

// Request emits the REQUEST sign.
// Asking another actor to perform action at peer level.
func (i *Actor) Request() {
	i.percept.Emit(i.subject, signMap[REQUEST])
}

// Command emits the COMMAND sign.
// Directing another actor to act with authority.
func (i *Actor) Command() {
	i.percept.Emit(i.subject, signMap[COMMAND])
}

// Acknowledge emits the ACKNOWLEDGE sign.
// Confirming receipt, understanding, or agreement.
func (i *Actor) Acknowledge() {
	i.percept.Emit(i.subject, signMap[ACKNOWLEDGE])
}

// Deny emits the DENY sign.
// Disagreeing with or correcting a proposition.
func (i *Actor) Deny() {
	i.percept.Emit(i.subject, signMap[DENY])
}

// Clarify emits the CLARIFY sign.
// Refining, specifying, or disambiguating intent.
func (i *Actor) Clarify() {
	i.percept.Emit(i.subject, signMap[CLARIFY])
}

// Promise emits the PROMISE sign.
// Committing to perform future action or deliver work.
func (i *Actor) Promise() {
	i.percept.Emit(i.subject, signMap[PROMISE])
}

// Deliver emits the DELIVER sign.
// Presenting completed work or fulfilled commitment.
func (i *Actor) Deliver() {
	i.percept.Emit(i.subject, signMap[DELIVER])
}
