// Code generated by opphav-gen-symbols. DO NOT EDIT.

package tasks

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "tasks"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// SUBMIT indicates task submitted to executor or queue.
	SUBMIT = signs.Define("SUBMIT")

	// REJECT indicates task submission rejected.
	REJECT = signs.Define("REJECT")

	// SCHEDULE indicates task scheduled for execution.
	SCHEDULE = signs.Define("SCHEDULE")

	// START indicates task execution begins.
	START = signs.Define("START")

	// PROGRESS indicates task reports progress.
	PROGRESS = signs.Define("PROGRESS")

	// SUSPEND indicates task paused or suspended.
	SUSPEND = signs.Define("SUSPEND")

	// RESUME indicates task resumed after suspension.
	RESUME = signs.Define("RESUME")

	// COMPLETE indicates task completed successfully.
	COMPLETE = signs.Define("COMPLETE")

	// FAIL indicates task failed with error.
	FAIL = signs.Define("FAIL")

	// CANCEL indicates task cancelled.
	CANCEL = signs.Define("CANCEL")

	// TIMEOUT indicates task exceeded execution time budget.
	TIMEOUT = signs.Define("TIMEOUT")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		SUBMIT:   opphav.KindOperation,
		REJECT:   opphav.KindOutcome,
		SCHEDULE: opphav.KindOperation,
		START:    opphav.KindOperation,
		PROGRESS: opphav.KindOperation,
		SUSPEND:  opphav.KindOperation,
		RESUME:   opphav.KindOperation,
		COMPLETE: opphav.KindOutcome,
		FAIL:     opphav.KindOutcome,
		CANCEL:   opphav.KindOperation,
		TIMEOUT:  opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Task struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Task {
	if percept == nil {
		panic("tasks: percept must not be nil")
	}

	return &Task{percept: percept, subject: subject}
}

// Submit emits the SUBMIT sign.
// Indicates task submitted to executor or queue.
func (i *Task) Submit() {
	i.percept.Emit(i.subject, signMap[SUBMIT])
}

// Reject emits the REJECT sign.
// Indicates task submission rejected.
func (i *Task) Reject() {
	i.percept.Emit(i.subject, signMap[REJECT])
}

// Schedule emits the SCHEDULE sign.
// Indicates task scheduled for execution.
func (i *Task) Schedule() {
	i.percept.Emit(i.subject, signMap[SCHEDULE])
}

// Start emits the START sign.
// Indicates task execution begins.
func (i *Task) Start() {
	i.percept.Emit(i.subject, signMap[START])
}

// Progress emits the PROGRESS sign.
// Indicates task reports progress.
func (i *Task) Progress() {
	i.percept.Emit(i.subject, signMap[PROGRESS])
}

// Suspend emits the SUSPEND sign.
// Indicates task paused or suspended.
func (i *Task) Suspend() {
	i.percept.Emit(i.subject, signMap[SUSPEND])
}

// Resume emits the RESUME sign.
// Indicates task resumed after suspension.
func (i *Task) Resume() {
	i.percept.Emit(i.subject, signMap[RESUME])
}

// Complete emits the COMPLETE sign.
// Indicates task completed successfully.
func (i *Task) Complete() {
	i.percept.Emit(i.subject, signMap[COMPLETE])
}

// Fail emits the FAIL sign.
// Indicates task failed with error.
func (i *Task) Fail() {
	i.percept.Emit(i.subject, signMap[FAIL])
}

// Cancel emits the CANCEL sign.
// Indicates task cancelled.
func (i *Task) Cancel() {
	i.percept.Emit(i.subject, signMap[CANCEL])
}

// Timeout emits the TIMEOUT sign.
// Indicates task exceeded execution time budget.
func (i *Task) Timeout() {
	i.percept.Emit(i.subject, signMap[TIMEOUT])
}
