// Code generated by opphav-gen-symbols. DO NOT EDIT.

package processes

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "processes"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// SPAWN indicates new process created.
	SPAWN = signs.Define("SPAWN")

	// START indicates process execution begins.
	START = signs.Define("START")

	// STOP indicates process stopped cleanly.
	STOP = signs.Define("STOP")

	// FAIL indicates process failed.
	FAIL = signs.Define("FAIL")

	// CRASH indicates process crashed.
	CRASH = signs.Define("CRASH")

	// KILL indicates process forcibly terminated.
	KILL = signs.Define("KILL")

	// RESTART indicates process being restarted.
	RESTART = signs.Define("RESTART")

	// SUSPEND indicates process suspended.
	SUSPEND = signs.Define("SUSPEND")

	// RESUME indicates process resumed after suspension.
	RESUME = signs.Define("RESUME")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		SPAWN:   opphav.KindOperation,
		START:   opphav.KindOperation,
		STOP:    opphav.KindOutcome,
		FAIL:    opphav.KindOutcome,
		CRASH:   opphav.KindOutcome,
		KILL:    opphav.KindOperation,
		RESTART: opphav.KindOperation,
		SUSPEND: opphav.KindOperation,
		RESUME:  opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Process struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Process {
	if percept == nil {
		panic("processes: percept must not be nil")
	}

	return &Process{percept: percept, subject: subject}
}

// Spawn emits the SPAWN sign.
// Indicates new process created.
func (i *Process) Spawn() {
	i.percept.Emit(i.subject, signMap[SPAWN])
}

// Start emits the START sign.
// Indicates process execution begins.
func (i *Process) Start() {
	i.percept.Emit(i.subject, signMap[START])
}

// Stop emits the STOP sign.
// Indicates process stopped cleanly.
func (i *Process) Stop() {
	i.percept.Emit(i.subject, signMap[STOP])
}

// Fail emits the FAIL sign.
// Indicates process failed.
func (i *Process) Fail() {
	i.percept.Emit(i.subject, signMap[FAIL])
}

// Crash emits the CRASH sign.
// Indicates process crashed.
func (i *Process) Crash() {
	i.percept.Emit(i.subject, signMap[CRASH])
}

// Kill emits the KILL sign.
// Indicates process forcibly terminated.
func (i *Process) Kill() {
	i.percept.Emit(i.subject, signMap[KILL])
}

// Restart emits the RESTART sign.
// Indicates process being restarted.
func (i *Process) Restart() {
	i.percept.Emit(i.subject, signMap[RESTART])
}

// Suspend emits the SUSPEND sign.
// Indicates process suspended.
func (i *Process) Suspend() {
	i.percept.Emit(i.subject, signMap[SUSPEND])
}

// Resume emits the RESUME sign.
// Indicates process resumed after suspension.
func (i *Process) Resume() {
	i.percept.Emit(i.subject, signMap[RESUME])
}
