// Code generated by opphav-gen-symbols. DO NOT EDIT.

package probes

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "probes"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// CONNECT indicates connection establishment
	CONNECT = signs.Define("CONNECT")

	// DISCONNECT indicates connection closure
	DISCONNECT = signs.Define("DISCONNECT")

	// TRANSFER indicates data transfer (sending or receiving, direction specified by dimension)
	TRANSFER = signs.Define("TRANSFER")

	// PROCESS indicates data processing
	PROCESS = signs.Define("PROCESS")

	// SUCCEED indicates successful completion
	SUCCEED = signs.Define("SUCCEED")

	// FAIL indicates failed completion
	FAIL = signs.Define("FAIL")
)

var (
	// OUTBOUND Outbound communication (initiated by self, sending outward)
	OUTBOUND = dimensions.Define("OUTBOUND")

	// INBOUND Inbound communication (received from other, coming inward)
	INBOUND = dimensions.Define("INBOUND")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		CONNECT:    opphav.KindOperation,
		DISCONNECT: opphav.KindOperation,
		TRANSFER:   opphav.KindOperation,
		PROCESS:    opphav.KindOperation,
		SUCCEED:    opphav.KindOutcome,
		FAIL:       opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Connect returns the CONNECT signal for the given dimension.
// Indicates connection establishment
func Connect(d Dimension) Signal {
	return signalMap[CONNECT][d].(Signal)
}

// Disconnect returns the DISCONNECT signal for the given dimension.
// Indicates connection closure
func Disconnect(d Dimension) Signal {
	return signalMap[DISCONNECT][d].(Signal)
}

// Transfer returns the TRANSFER signal for the given dimension.
// Indicates data transfer (sending or receiving, direction specified by dimension)
func Transfer(d Dimension) Signal {
	return signalMap[TRANSFER][d].(Signal)
}

// Process returns the PROCESS signal for the given dimension.
// Indicates data processing
func Process(d Dimension) Signal {
	return signalMap[PROCESS][d].(Signal)
}

// Succeed returns the SUCCEED signal for the given dimension.
// Indicates successful completion
func Succeed(d Dimension) Signal {
	return signalMap[SUCCEED][d].(Signal)
}

// Fail returns the FAIL signal for the given dimension.
// Indicates failed completion
func Fail(d Dimension) Signal {
	return signalMap[FAIL][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Probe struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Probe {
	if percept == nil {
		panic("probes: percept must not be nil")
	}

	return &Probe{percept: percept, subject: subject}
}

// Connect emits the CONNECT signal.
// Indicates connection establishment
func (i *Probe) Connect(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CONNECT][d])
}

// Disconnect emits the DISCONNECT signal.
// Indicates connection closure
func (i *Probe) Disconnect(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DISCONNECT][d])
}

// Transfer emits the TRANSFER signal.
// Indicates data transfer (sending or receiving, direction specified by dimension)
func (i *Probe) Transfer(d Dimension) {
	i.percept.Emit(i.subject, signalMap[TRANSFER][d])
}

// Process emits the PROCESS signal.
// Indicates data processing
func (i *Probe) Process(d Dimension) {
	i.percept.Emit(i.subject, signalMap[PROCESS][d])
}

// Succeed emits the SUCCEED signal.
// Indicates successful completion
func (i *Probe) Succeed(d Dimension) {
	i.percept.Emit(i.subject, signalMap[SUCCEED][d])
}

// Fail emits the FAIL signal.
// Indicates failed completion
func (i *Probe) Fail(d Dimension) {
	i.percept.Emit(i.subject, signalMap[FAIL][d])
}
