// Code generated by opphav-gen-symbols. DO NOT EDIT.

package pools

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "pools"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// EXPAND indicates the pool's capacity increased.
	EXPAND = signs.Define("EXPAND")

	// CONTRACT indicates the pool's capacity decreased.
	CONTRACT = signs.Define("CONTRACT")

	// BORROW indicates a resource was borrowed from the pool.
	BORROW = signs.Define("BORROW")

	// RECLAIM indicates a resource was reclaimed by the pool.
	RECLAIM = signs.Define("RECLAIM")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Pool struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Pool {
	if percept == nil {
		panic("pools: percept must not be nil")
	}

	return &Pool{percept: percept, subject: subject}
}

// Expand emits the EXPAND sign.
// Indicates the pool's capacity increased.
func (i *Pool) Expand() {
	i.percept.Emit(i.subject, signMap[EXPAND])
}

// Contract emits the CONTRACT sign.
// Indicates the pool's capacity decreased.
func (i *Pool) Contract() {
	i.percept.Emit(i.subject, signMap[CONTRACT])
}

// Borrow emits the BORROW sign.
// Indicates a resource was borrowed from the pool.
func (i *Pool) Borrow() {
	i.percept.Emit(i.subject, signMap[BORROW])
}

// Reclaim emits the RECLAIM sign.
// Indicates a resource was reclaimed by the pool.
func (i *Pool) Reclaim() {
	i.percept.Emit(i.subject, signMap[RECLAIM])
}
