// Code generated by opphav-gen-symbols. DO NOT EDIT.

package exchanges

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "exchanges"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// CONTRACT Commit to participate in an exchange.
	CONTRACT = signs.Define("CONTRACT")

	// TRANSFER Resource changes hands.
	TRANSFER = signs.Define("TRANSFER")
)

var (
	// PROVIDER The giving perspective in an exchange.
	PROVIDER = dimensions.Define("PROVIDER")

	// RECEIVER The receiving perspective in an exchange.
	RECEIVER = dimensions.Define("RECEIVER")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}
}

// Contract returns the CONTRACT signal for the given dimension.
// Commit to participate in an exchange.
func Contract(d Dimension) Signal {
	return signalMap[CONTRACT][d].(Signal)
}

// Transfer returns the TRANSFER signal for the given dimension.
// Resource changes hands.
func Transfer(d Dimension) Signal {
	return signalMap[TRANSFER][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

type Exchange struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Exchange {
	if percept == nil {
		panic("exchanges: percept must not be nil")
	}

	return &Exchange{percept: percept, subject: subject}
}

// Contract emits the CONTRACT signal.
// Commit to participate in an exchange.
func (i *Exchange) Contract(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CONTRACT][d])
}

// Transfer emits the TRANSFER signal.
// Resource changes hands.
func (i *Exchange) Transfer(d Dimension) {
	i.percept.Emit(i.subject, signalMap[TRANSFER][d])
}
