// Code generated by opphav-gen-symbols. DO NOT EDIT.

package stacks

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "stacks"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// PUSH indicates an item was successfully added to the stack (top).
	PUSH = signs.Define("PUSH")

	// POP indicates an item was successfully removed from the stack (top).
	POP = signs.Define("POP")

	// OVERFLOW indicates the stack reached capacity and rejected a PUSH operation.
	OVERFLOW = signs.Define("OVERFLOW")

	// UNDERFLOW indicates the stack was empty and could not satisfy a POP operation.
	UNDERFLOW = signs.Define("UNDERFLOW")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Stack struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Stack {
	if percept == nil {
		panic("stacks: percept must not be nil")
	}

	return &Stack{percept: percept, subject: subject}
}

// Push emits the PUSH sign.
// Indicates an item was successfully added to the stack (top).
func (i *Stack) Push() {
	i.percept.Emit(i.subject, signMap[PUSH])
}

// Pop emits the POP sign.
// Indicates an item was successfully removed from the stack (top).
func (i *Stack) Pop() {
	i.percept.Emit(i.subject, signMap[POP])
}

// Overflow emits the OVERFLOW sign.
// Indicates the stack reached capacity and rejected a PUSH operation.
func (i *Stack) Overflow() {
	i.percept.Emit(i.subject, signMap[OVERFLOW])
}

// Underflow emits the UNDERFLOW sign.
// Indicates the stack was empty and could not satisfy a POP operation.
func (i *Stack) Underflow() {
	i.percept.Emit(i.subject, signMap[UNDERFLOW])
}
