// Code generated by opphav-gen-symbols. DO NOT EDIT.

package logs

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "logs"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// SEVERE indicates a serious failure or error condition.
	SEVERE = signs.Define("SEVERE")

	// WARNING indicates a potential problem or concerning condition.
	WARNING = signs.Define("WARNING")

	// INFO indicates normal operational information.
	INFO = signs.Define("INFO")

	// DEBUG indicates diagnostic or tracing information.
	DEBUG = signs.Define("DEBUG")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		SEVERE:  opphav.KindOutcome,
		WARNING: opphav.KindOutcome,
		INFO:    opphav.KindOutcome,
		DEBUG:   opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Log struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Log {
	if percept == nil {
		panic("logs: percept must not be nil")
	}

	return &Log{percept: percept, subject: subject}
}

// Severe emits the SEVERE sign.
// Indicates a serious failure or error condition.
func (i *Log) Severe() {
	i.percept.Emit(i.subject, signMap[SEVERE])
}

// Warning emits the WARNING sign.
// Indicates a potential problem or concerning condition.
func (i *Log) Warning() {
	i.percept.Emit(i.subject, signMap[WARNING])
}

// Info emits the INFO sign.
// Indicates normal operational information.
func (i *Log) Info() {
	i.percept.Emit(i.subject, signMap[INFO])
}

// Debug emits the DEBUG sign.
// Indicates diagnostic or tracing information.
func (i *Log) Debug() {
	i.percept.Emit(i.subject, signMap[DEBUG])
}
