// Code generated by opphav-gen-symbols. DO NOT EDIT.

package flows

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "flows"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// SUCCESS indicates successful transition through a stage.
	SUCCESS = signs.Define("SUCCESS")

	// FAIL indicates failed transition through a stage.
	FAIL = signs.Define("FAIL")
)

var (
	// INGRESS Signals emitted at the entry point of a flow.
	INGRESS = dimensions.Define("INGRESS")

	// TRANSIT Signals emitted during processing/movement of a flow.
	TRANSIT = dimensions.Define("TRANSIT")

	// EGRESS Signals emitted at the exit point of a flow.
	EGRESS = dimensions.Define("EGRESS")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		SUCCESS: opphav.KindOutcome,
		FAIL:    opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Success returns the SUCCESS signal for the given dimension.
// Indicates successful transition through a stage.
func Success(d Dimension) Signal {
	return signalMap[SUCCESS][d].(Signal)
}

// Fail returns the FAIL signal for the given dimension.
// Indicates failed transition through a stage.
func Fail(d Dimension) Signal {
	return signalMap[FAIL][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Flow struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Flow {
	if percept == nil {
		panic("flows: percept must not be nil")
	}

	return &Flow{percept: percept, subject: subject}
}

// Success emits the SUCCESS signal.
// Indicates successful transition through a stage.
func (i *Flow) Success(d Dimension) {
	i.percept.Emit(i.subject, signalMap[SUCCESS][d])
}

// Fail emits the FAIL signal.
// Indicates failed transition through a stage.
func (i *Flow) Fail(d Dimension) {
	i.percept.Emit(i.subject, signalMap[FAIL][d])
}
