// Code generated by opphav-gen-symbols. DO NOT EDIT.

package resources

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "resources"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// ATTEMPT A non-blocking request for units from a resource.
	ATTEMPT = signs.Define("ATTEMPT")

	// ACQUIRE A blocking or wait-based request for units from a resource.
	ACQUIRE = signs.Define("ACQUIRE")

	// GRANT The successful granting of a request for units from a resource.
	GRANT = signs.Define("GRANT")

	// DENY The denial of a request due to insufficient resource capacity.
	DENY = signs.Define("DENY")

	// TIMEOUT The expiration of a blocking request due to wait time exceeding configured limits.
	TIMEOUT = signs.Define("TIMEOUT")

	// RELEASE The return of previously granted resource units back to the resource pool.
	RELEASE = signs.Define("RELEASE")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		ATTEMPT: opphav.KindOperation,
		ACQUIRE: opphav.KindOperation,
		GRANT:   opphav.KindOutcome,
		DENY:    opphav.KindOutcome,
		TIMEOUT: opphav.KindOutcome,
		RELEASE: opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Resource struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Resource {
	if percept == nil {
		panic("resources: percept must not be nil")
	}

	return &Resource{percept: percept, subject: subject}
}

// Attempt emits the ATTEMPT sign.
// A non-blocking request for units from a resource.
func (i *Resource) Attempt() {
	i.percept.Emit(i.subject, signMap[ATTEMPT])
}

// Acquire emits the ACQUIRE sign.
// A blocking or wait-based request for units from a resource.
func (i *Resource) Acquire() {
	i.percept.Emit(i.subject, signMap[ACQUIRE])
}

// Grant emits the GRANT sign.
// The successful granting of a request for units from a resource.
func (i *Resource) Grant() {
	i.percept.Emit(i.subject, signMap[GRANT])
}

// Deny emits the DENY sign.
// The denial of a request due to insufficient resource capacity.
func (i *Resource) Deny() {
	i.percept.Emit(i.subject, signMap[DENY])
}

// Timeout emits the TIMEOUT sign.
// The expiration of a blocking request due to wait time exceeding configured limits.
func (i *Resource) Timeout() {
	i.percept.Emit(i.subject, signMap[TIMEOUT])
}

// Release emits the RELEASE sign.
// The return of previously granted resource units back to the resource pool.
func (i *Resource) Release() {
	i.percept.Emit(i.subject, signMap[RELEASE])
}
