// Code generated by opphav-gen-symbols. DO NOT EDIT.

package trends

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "trends"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// STABLE indicates the process is in statistical control with no significant pattern.
	STABLE = signs.Define("STABLE")

	// DRIFT indicates sustained movement away from the baseline.
	DRIFT = signs.Define("DRIFT")

	// SPIKE indicates a sudden extreme deviation (outlier).
	SPIKE = signs.Define("SPIKE")

	// CYCLE indicates an oscillating pattern.
	CYCLE = signs.Define("CYCLE")

	// CHAOS indicates erratic, chaotic variation.
	CHAOS = signs.Define("CHAOS")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Trend struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Trend {
	if percept == nil {
		panic("trends: percept must not be nil")
	}

	return &Trend{percept: percept, subject: subject}
}

// Stable emits the STABLE sign.
// Indicates the process is in statistical control with no significant pattern.
func (i *Trend) Stable() {
	i.percept.Emit(i.subject, signMap[STABLE])
}

// Drift emits the DRIFT sign.
// Indicates sustained movement away from the baseline.
func (i *Trend) Drift() {
	i.percept.Emit(i.subject, signMap[DRIFT])
}

// Spike emits the SPIKE sign.
// Indicates a sudden extreme deviation (outlier).
func (i *Trend) Spike() {
	i.percept.Emit(i.subject, signMap[SPIKE])
}

// Cycle emits the CYCLE sign.
// Indicates an oscillating pattern.
func (i *Trend) Cycle() {
	i.percept.Emit(i.subject, signMap[CYCLE])
}

// Chaos emits the CHAOS sign.
// Indicates erratic, chaotic variation.
func (i *Trend) Chaos() {
	i.percept.Emit(i.subject, signMap[CHAOS])
}
