// Code generated by opphav-gen-symbols. DO NOT EDIT.

package gauges

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "gauges"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// INCREMENT indicates the gauge was incremented.
	INCREMENT = signs.Define("INCREMENT")

	// DECREMENT indicates the gauge was decremented.
	DECREMENT = signs.Define("DECREMENT")

	// OVERFLOW indicates the gauge exceeded its maximum value.
	OVERFLOW = signs.Define("OVERFLOW")

	// UNDERFLOW indicates the gauge fell below its minimum value.
	UNDERFLOW = signs.Define("UNDERFLOW")

	// RESET indicates the gauge was explicitly reset to baseline.
	RESET = signs.Define("RESET")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Gauge struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Gauge {
	if percept == nil {
		panic("gauges: percept must not be nil")
	}

	return &Gauge{percept: percept, subject: subject}
}

// Increment emits the INCREMENT sign.
// Indicates the gauge was incremented.
func (i *Gauge) Increment() {
	i.percept.Emit(i.subject, signMap[INCREMENT])
}

// Decrement emits the DECREMENT sign.
// Indicates the gauge was decremented.
func (i *Gauge) Decrement() {
	i.percept.Emit(i.subject, signMap[DECREMENT])
}

// Overflow emits the OVERFLOW sign.
// Indicates the gauge exceeded its maximum value.
func (i *Gauge) Overflow() {
	i.percept.Emit(i.subject, signMap[OVERFLOW])
}

// Underflow emits the UNDERFLOW sign.
// Indicates the gauge fell below its minimum value.
func (i *Gauge) Underflow() {
	i.percept.Emit(i.subject, signMap[UNDERFLOW])
}

// Reset emits the RESET sign.
// Indicates the gauge was explicitly reset to baseline.
func (i *Gauge) Reset() {
	i.percept.Emit(i.subject, signMap[RESET])
}
