// Code generated by opphav-gen-symbols. DO NOT EDIT.

package statuses

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "statuses"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.SpectrumEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewSpectrumSet(
		domain,
		func(e opphav.SpectrumEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// CONVERGING indicates the subject of observation is stabilizing towards reliable operation,
	CONVERGING = signs.Define("CONVERGING")

	// STABLE indicates the subject of observation is operating within expected parameters,
	STABLE = signs.Define("STABLE")

	// DIVERGING indicates the subject of observation is destabilizing, with increasing variations
	DIVERGING = signs.Define("DIVERGING")

	// ERRATIC indicates the subject of observation is exhibiting unpredictable behavior with
	ERRATIC = signs.Define("ERRATIC")

	// DEGRADED indicates the subject of observation is partially operational, with reduced
	DEGRADED = signs.Define("DEGRADED")

	// DEFECTIVE indicates the subject of observation is unreliable, with predominantly failed
	DEFECTIVE = signs.Define("DEFECTIVE")

	// DOWN indicates the subject of observation is entirely non-operational and unable to process any requests
	DOWN = signs.Define("DOWN")
)

var (
	// TENTATIVE indicates a preliminary assessment based on initial behavioral patterns.
	TENTATIVE = dimensions.Define("TENTATIVE")

	// MEASURED indicates an established assessment with strong evidence for the condition classification.
	MEASURED = dimensions.Define("MEASURED")

	// CONFIRMED indicates a definitive assessment with unambiguous evidence for the condition classification.
	CONFIRMED = dimensions.Define("CONFIRMED")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}
}

// Converging returns the CONVERGING signal for the given dimension.
// Indicates the subject of observation is stabilizing towards reliable operation,
func Converging(d Dimension) Signal {
	return signalMap[CONVERGING][d].(Signal)
}

// Stable returns the STABLE signal for the given dimension.
// Indicates the subject of observation is operating within expected parameters,
func Stable(d Dimension) Signal {
	return signalMap[STABLE][d].(Signal)
}

// Diverging returns the DIVERGING signal for the given dimension.
// Indicates the subject of observation is destabilizing, with increasing variations
func Diverging(d Dimension) Signal {
	return signalMap[DIVERGING][d].(Signal)
}

// Erratic returns the ERRATIC signal for the given dimension.
// Indicates the subject of observation is exhibiting unpredictable behavior with
func Erratic(d Dimension) Signal {
	return signalMap[ERRATIC][d].(Signal)
}

// Degraded returns the DEGRADED signal for the given dimension.
// Indicates the subject of observation is partially operational, with reduced
func Degraded(d Dimension) Signal {
	return signalMap[DEGRADED][d].(Signal)
}

// Defective returns the DEFECTIVE signal for the given dimension.
// Indicates the subject of observation is unreliable, with predominantly failed
func Defective(d Dimension) Signal {
	return signalMap[DEFECTIVE][d].(Signal)
}

// Down returns the DOWN signal for the given dimension.
// Indicates the subject of observation is entirely non-operational and unable to process any requests
func Down(d Dimension) Signal {
	return signalMap[DOWN][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

type Status struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Status {
	if percept == nil {
		panic("statuses: percept must not be nil")
	}

	return &Status{percept: percept, subject: subject}
}

// Converging emits the CONVERGING signal.
// Indicates the subject of observation is stabilizing towards reliable operation,
func (i *Status) Converging(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CONVERGING][d])
}

// Stable emits the STABLE signal.
// Indicates the subject of observation is operating within expected parameters,
func (i *Status) Stable(d Dimension) {
	i.percept.Emit(i.subject, signalMap[STABLE][d])
}

// Diverging emits the DIVERGING signal.
// Indicates the subject of observation is destabilizing, with increasing variations
func (i *Status) Diverging(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DIVERGING][d])
}

// Erratic emits the ERRATIC signal.
// Indicates the subject of observation is exhibiting unpredictable behavior with
func (i *Status) Erratic(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ERRATIC][d])
}

// Degraded emits the DEGRADED signal.
// Indicates the subject of observation is partially operational, with reduced
func (i *Status) Degraded(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DEGRADED][d])
}

// Defective emits the DEFECTIVE signal.
// Indicates the subject of observation is unreliable, with predominantly failed
func (i *Status) Defective(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DEFECTIVE][d])
}

// Down emits the DOWN signal.
// Indicates the subject of observation is entirely non-operational and unable to process any requests
func (i *Status) Down(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DOWN][d])
}
