// Code generated by opphav-gen-symbols. DO NOT EDIT.

package latches

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "latches"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// AWAIT indicates a thread is waiting at the barrier (blocking).
	AWAIT = signs.Define("AWAIT")

	// ARRIVE indicates a thread/participant has reached the barrier or decremented the count.
	ARRIVE = signs.Define("ARRIVE")

	// RELEASE indicates the barrier condition is satisfied and waiting threads are unblocked.
	RELEASE = signs.Define("RELEASE")

	// TIMEOUT indicates a waiting thread's timeout was exceeded before barrier satisfaction.
	TIMEOUT = signs.Define("TIMEOUT")

	// RESET indicates the barrier was reset for reuse in cyclic coordination.
	RESET = signs.Define("RESET")

	// ABANDON indicates a participant terminated without arriving at the barrier.
	ABANDON = signs.Define("ABANDON")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		AWAIT:   opphav.KindOperation,
		ARRIVE:  opphav.KindOperation,
		RELEASE: opphav.KindOutcome,
		TIMEOUT: opphav.KindOutcome,
		RESET:   opphav.KindOperation,
		ABANDON: opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Latch struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Latch {
	if percept == nil {
		panic("latches: percept must not be nil")
	}

	return &Latch{percept: percept, subject: subject}
}

// Await emits the AWAIT sign.
// Indicates a thread is waiting at the barrier (blocking).
func (i *Latch) Await() {
	i.percept.Emit(i.subject, signMap[AWAIT])
}

// Arrive emits the ARRIVE sign.
// Indicates a thread/participant has reached the barrier or decremented the count.
func (i *Latch) Arrive() {
	i.percept.Emit(i.subject, signMap[ARRIVE])
}

// Release emits the RELEASE sign.
// Indicates the barrier condition is satisfied and waiting threads are unblocked.
func (i *Latch) Release() {
	i.percept.Emit(i.subject, signMap[RELEASE])
}

// Timeout emits the TIMEOUT sign.
// Indicates a waiting thread's timeout was exceeded before barrier satisfaction.
func (i *Latch) Timeout() {
	i.percept.Emit(i.subject, signMap[TIMEOUT])
}

// Reset emits the RESET sign.
// Indicates the barrier was reset for reuse in cyclic coordination.
func (i *Latch) Reset() {
	i.percept.Emit(i.subject, signMap[RESET])
}

// Abandon emits the ABANDON sign.
// Indicates a participant terminated without arriving at the barrier.
func (i *Latch) Abandon() {
	i.percept.Emit(i.subject, signMap[ABANDON])
}
