// Code generated by opphav-gen-symbols. DO NOT EDIT.

package caches

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "caches"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// LOOKUP indicates an attempt to retrieve an entry from the cache.
	LOOKUP = signs.Define("LOOKUP")

	// HIT indicates a cache lookup succeeded - the requested entry was found.
	HIT = signs.Define("HIT")

	// MISS indicates a cache lookup failed - the requested entry was not found.
	MISS = signs.Define("MISS")

	// STORE indicates an entry was added to or updated in the cache.
	STORE = signs.Define("STORE")

	// EVICT indicates an entry was automatically removed due to capacity or policy.
	EVICT = signs.Define("EVICT")

	// EXPIRE indicates an entry was removed because it reached its time-to-live (TTL).
	EXPIRE = signs.Define("EXPIRE")

	// REMOVE indicates an entry was explicitly removed or invalidated.
	REMOVE = signs.Define("REMOVE")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		LOOKUP: opphav.KindOperation,
		HIT:    opphav.KindOutcome,
		MISS:   opphav.KindOutcome,
		STORE:  opphav.KindOperation,
		EVICT:  opphav.KindOutcome,
		EXPIRE: opphav.KindOutcome,
		REMOVE: opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Cache struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Cache {
	if percept == nil {
		panic("caches: percept must not be nil")
	}

	return &Cache{percept: percept, subject: subject}
}

// Lookup emits the LOOKUP sign.
// Indicates an attempt to retrieve an entry from the cache.
func (i *Cache) Lookup() {
	i.percept.Emit(i.subject, signMap[LOOKUP])
}

// Hit emits the HIT sign.
// Indicates a cache lookup succeeded - the requested entry was found.
func (i *Cache) Hit() {
	i.percept.Emit(i.subject, signMap[HIT])
}

// Miss emits the MISS sign.
// Indicates a cache lookup failed - the requested entry was not found.
func (i *Cache) Miss() {
	i.percept.Emit(i.subject, signMap[MISS])
}

// Store emits the STORE sign.
// Indicates an entry was added to or updated in the cache.
func (i *Cache) Store() {
	i.percept.Emit(i.subject, signMap[STORE])
}

// Evict emits the EVICT sign.
// Indicates an entry was automatically removed due to capacity or policy.
func (i *Cache) Evict() {
	i.percept.Emit(i.subject, signMap[EVICT])
}

// Expire emits the EXPIRE sign.
// Indicates an entry was removed because it reached its time-to-live (TTL).
func (i *Cache) Expire() {
	i.percept.Emit(i.subject, signMap[EXPIRE])
}

// Remove emits the REMOVE sign.
// Indicates an entry was explicitly removed or invalidated.
func (i *Cache) Remove() {
	i.percept.Emit(i.subject, signMap[REMOVE])
}
