// Code generated by opphav-gen-symbols. DO NOT EDIT.

package situations

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "situations"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.SpectrumEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewSpectrumSet(
		domain,
		func(e opphav.SpectrumEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// NORMAL The situation poses no immediate concern and requires no intervention.
	NORMAL = signs.Define("NORMAL")

	// WARNING The situation requires attention but is not yet critical.
	WARNING = signs.Define("WARNING")

	// CRITICAL The situation is serious and demands prompt intervention.
	CRITICAL = signs.Define("CRITICAL")
)

var (
	// CONSTANT The situation exhibits no variation, maintaining an unchanging level.
	CONSTANT = dimensions.Define("CONSTANT")

	// VARIABLE The situation exhibits moderate variation and fluctuation.
	VARIABLE = dimensions.Define("VARIABLE")

	// VOLATILE The situation exhibits high instability with rapid, chaotic changes.
	VOLATILE = dimensions.Define("VOLATILE")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}
}

// Normal returns the NORMAL signal for the given dimension.
// The situation poses no immediate concern and requires no intervention.
func Normal(d Dimension) Signal {
	return signalMap[NORMAL][d].(Signal)
}

// Warning returns the WARNING signal for the given dimension.
// The situation requires attention but is not yet critical.
func Warning(d Dimension) Signal {
	return signalMap[WARNING][d].(Signal)
}

// Critical returns the CRITICAL signal for the given dimension.
// The situation is serious and demands prompt intervention.
func Critical(d Dimension) Signal {
	return signalMap[CRITICAL][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

type Situation struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Situation {
	if percept == nil {
		panic("situations: percept must not be nil")
	}

	return &Situation{percept: percept, subject: subject}
}

// Normal emits the NORMAL signal.
// The situation poses no immediate concern and requires no intervention.
func (i *Situation) Normal(d Dimension) {
	i.percept.Emit(i.subject, signalMap[NORMAL][d])
}

// Warning emits the WARNING signal.
// The situation requires attention but is not yet critical.
func (i *Situation) Warning(d Dimension) {
	i.percept.Emit(i.subject, signalMap[WARNING][d])
}

// Critical emits the CRITICAL signal.
// The situation is serious and demands prompt intervention.
func (i *Situation) Critical(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CRITICAL][d])
}
