// Code generated by opphav-gen-symbols. DO NOT EDIT.

package counters

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "counters"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// INCREMENT indicates the counter was incremented.
	INCREMENT = signs.Define("INCREMENT")

	// OVERFLOW indicates the counter exceeded its maximum value and wrapped.
	OVERFLOW = signs.Define("OVERFLOW")

	// RESET indicates the counter was explicitly reset to zero.
	RESET = signs.Define("RESET")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Counter struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Counter {
	if percept == nil {
		panic("counters: percept must not be nil")
	}

	return &Counter{percept: percept, subject: subject}
}

// Increment emits the INCREMENT sign.
// Indicates the counter was incremented.
func (i *Counter) Increment() {
	i.percept.Emit(i.subject, signMap[INCREMENT])
}

// Overflow emits the OVERFLOW sign.
// Indicates the counter exceeded its maximum value and wrapped.
func (i *Counter) Overflow() {
	i.percept.Emit(i.subject, signMap[OVERFLOW])
}

// Reset emits the RESET sign.
// Indicates the counter was explicitly reset to zero.
func (i *Counter) Reset() {
	i.percept.Emit(i.subject, signMap[RESET])
}
