// Code generated by opphav-gen-symbols. DO NOT EDIT.

package atomics

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "atomics"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// ATTEMPT indicates a CAS operation has been initiated.
	ATTEMPT = signs.Define("ATTEMPT")

	// SUCCESS indicates the CAS operation succeeded.
	SUCCESS = signs.Define("SUCCESS")

	// FAIL indicates the CAS operation failed due to contention.
	FAIL = signs.Define("FAIL")

	// SPIN indicates busy-wait retry in a spin loop.
	SPIN = signs.Define("SPIN")

	// YIELD indicates Thread.yield() applied as scheduling hint.
	YIELD = signs.Define("YIELD")

	// BACKOFF indicates deliberate delay applied between retries.
	BACKOFF = signs.Define("BACKOFF")

	// PARK indicates transition from spinning to blocking.
	PARK = signs.Define("PARK")

	// EXHAUST indicates retry budget exceeded, operation abandoned.
	EXHAUST = signs.Define("EXHAUST")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		ATTEMPT: opphav.KindOperation,
		SUCCESS: opphav.KindOutcome,
		FAIL:    opphav.KindOutcome,
		SPIN:    opphav.KindOperation,
		YIELD:   opphav.KindOperation,
		BACKOFF: opphav.KindOperation,
		PARK:    opphav.KindOperation,
		EXHAUST: opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Atomic struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Atomic {
	if percept == nil {
		panic("atomics: percept must not be nil")
	}

	return &Atomic{percept: percept, subject: subject}
}

// Attempt emits the ATTEMPT sign.
// Indicates a CAS operation has been initiated.
func (i *Atomic) Attempt() {
	i.percept.Emit(i.subject, signMap[ATTEMPT])
}

// Success emits the SUCCESS sign.
// Indicates the CAS operation succeeded.
func (i *Atomic) Success() {
	i.percept.Emit(i.subject, signMap[SUCCESS])
}

// Fail emits the FAIL sign.
// Indicates the CAS operation failed due to contention.
func (i *Atomic) Fail() {
	i.percept.Emit(i.subject, signMap[FAIL])
}

// Spin emits the SPIN sign.
// Indicates busy-wait retry in a spin loop.
func (i *Atomic) Spin() {
	i.percept.Emit(i.subject, signMap[SPIN])
}

// Yield emits the YIELD sign.
// Indicates Thread.yield() applied as scheduling hint.
func (i *Atomic) Yield() {
	i.percept.Emit(i.subject, signMap[YIELD])
}

// Backoff emits the BACKOFF sign.
// Indicates deliberate delay applied between retries.
func (i *Atomic) Backoff() {
	i.percept.Emit(i.subject, signMap[BACKOFF])
}

// Park emits the PARK sign.
// Indicates transition from spinning to blocking.
func (i *Atomic) Park() {
	i.percept.Emit(i.subject, signMap[PARK])
}

// Exhaust emits the EXHAUST sign.
// Indicates retry budget exceeded, operation abandoned.
func (i *Atomic) Exhaust() {
	i.percept.Emit(i.subject, signMap[EXHAUST])
}
