// Code generated by opphav-gen-symbols. DO NOT EDIT.

package valves

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "valves"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// PASS indicates a request was allowed through the valve.
	PASS = signs.Define("PASS")

	// DENY indicates a request was blocked by the valve.
	DENY = signs.Define("DENY")

	// EXPAND indicates the valve increased its capacity.
	EXPAND = signs.Define("EXPAND")

	// CONTRACT indicates the valve decreased its capacity.
	CONTRACT = signs.Define("CONTRACT")

	// DROP indicates a request was dropped due to overload.
	DROP = signs.Define("DROP")

	// DRAIN indicates the valve is clearing backlog during recovery.
	DRAIN = signs.Define("DRAIN")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		PASS:     opphav.KindOutcome,
		DENY:     opphav.KindOutcome,
		EXPAND:   opphav.KindOperation,
		CONTRACT: opphav.KindOperation,
		DROP:     opphav.KindOperation,
		DRAIN:    opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Valve struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Valve {
	if percept == nil {
		panic("valves: percept must not be nil")
	}

	return &Valve{percept: percept, subject: subject}
}

// Pass emits the PASS sign.
// Indicates a request was allowed through the valve.
func (i *Valve) Pass() {
	i.percept.Emit(i.subject, signMap[PASS])
}

// Deny emits the DENY sign.
// Indicates a request was blocked by the valve.
func (i *Valve) Deny() {
	i.percept.Emit(i.subject, signMap[DENY])
}

// Expand emits the EXPAND sign.
// Indicates the valve increased its capacity.
func (i *Valve) Expand() {
	i.percept.Emit(i.subject, signMap[EXPAND])
}

// Contract emits the CONTRACT sign.
// Indicates the valve decreased its capacity.
func (i *Valve) Contract() {
	i.percept.Emit(i.subject, signMap[CONTRACT])
}

// Drop emits the DROP sign.
// Indicates a request was dropped due to overload.
func (i *Valve) Drop() {
	i.percept.Emit(i.subject, signMap[DROP])
}

// Drain emits the DRAIN sign.
// Indicates the valve is clearing backlog during recovery.
func (i *Valve) Drain() {
	i.percept.Emit(i.subject, signMap[DRAIN])
}
