// Code generated by opphav-gen-symbols. DO NOT EDIT.

package transactions

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "transactions"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// START indicates transaction initiation.
	START = signs.Define("START")

	// PREPARE indicates the voting/prepare phase of two-phase commit.
	PREPARE = signs.Define("PREPARE")

	// COMMIT indicates transaction commitment.
	COMMIT = signs.Define("COMMIT")

	// ROLLBACK indicates transaction rollback.
	ROLLBACK = signs.Define("ROLLBACK")

	// ABORT indicates forced transaction termination.
	ABORT = signs.Define("ABORT")

	// EXPIRE indicates transaction expiration.
	EXPIRE = signs.Define("EXPIRE")

	// CONFLICT indicates write conflict or constraint violation.
	CONFLICT = signs.Define("CONFLICT")

	// COMPENSATE indicates compensating action in saga pattern.
	COMPENSATE = signs.Define("COMPENSATE")
)

var (
	// COORDINATOR The emission of a transaction signal from the coordinator's perspective.
	COORDINATOR = dimensions.Define("COORDINATOR")

	// PARTICIPANT The reception of a transaction signal from a participant's perspective.
	PARTICIPANT = dimensions.Define("PARTICIPANT")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		START:      opphav.KindOperation,
		PREPARE:    opphav.KindOperation,
		COMMIT:     opphav.KindOutcome,
		ROLLBACK:   opphav.KindOutcome,
		ABORT:      opphav.KindOutcome,
		EXPIRE:     opphav.KindOutcome,
		CONFLICT:   opphav.KindOutcome,
		COMPENSATE: opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Start returns the START signal for the given dimension.
// Indicates transaction initiation.
func Start(d Dimension) Signal {
	return signalMap[START][d].(Signal)
}

// Prepare returns the PREPARE signal for the given dimension.
// Indicates the voting/prepare phase of two-phase commit.
func Prepare(d Dimension) Signal {
	return signalMap[PREPARE][d].(Signal)
}

// Commit returns the COMMIT signal for the given dimension.
// Indicates transaction commitment.
func Commit(d Dimension) Signal {
	return signalMap[COMMIT][d].(Signal)
}

// Rollback returns the ROLLBACK signal for the given dimension.
// Indicates transaction rollback.
func Rollback(d Dimension) Signal {
	return signalMap[ROLLBACK][d].(Signal)
}

// Abort returns the ABORT signal for the given dimension.
// Indicates forced transaction termination.
func Abort(d Dimension) Signal {
	return signalMap[ABORT][d].(Signal)
}

// Expire returns the EXPIRE signal for the given dimension.
// Indicates transaction expiration.
func Expire(d Dimension) Signal {
	return signalMap[EXPIRE][d].(Signal)
}

// Conflict returns the CONFLICT signal for the given dimension.
// Indicates write conflict or constraint violation.
func Conflict(d Dimension) Signal {
	return signalMap[CONFLICT][d].(Signal)
}

// Compensate returns the COMPENSATE signal for the given dimension.
// Indicates compensating action in saga pattern.
func Compensate(d Dimension) Signal {
	return signalMap[COMPENSATE][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Transaction struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Transaction {
	if percept == nil {
		panic("transactions: percept must not be nil")
	}

	return &Transaction{percept: percept, subject: subject}
}

// Start emits the START signal.
// Indicates transaction initiation.
func (i *Transaction) Start(d Dimension) {
	i.percept.Emit(i.subject, signalMap[START][d])
}

// Prepare emits the PREPARE signal.
// Indicates the voting/prepare phase of two-phase commit.
func (i *Transaction) Prepare(d Dimension) {
	i.percept.Emit(i.subject, signalMap[PREPARE][d])
}

// Commit emits the COMMIT signal.
// Indicates transaction commitment.
func (i *Transaction) Commit(d Dimension) {
	i.percept.Emit(i.subject, signalMap[COMMIT][d])
}

// Rollback emits the ROLLBACK signal.
// Indicates transaction rollback.
func (i *Transaction) Rollback(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ROLLBACK][d])
}

// Abort emits the ABORT signal.
// Indicates forced transaction termination.
func (i *Transaction) Abort(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ABORT][d])
}

// Expire emits the EXPIRE signal.
// Indicates transaction expiration.
func (i *Transaction) Expire(d Dimension) {
	i.percept.Emit(i.subject, signalMap[EXPIRE][d])
}

// Conflict emits the CONFLICT signal.
// Indicates write conflict or constraint violation.
func (i *Transaction) Conflict(d Dimension) {
	i.percept.Emit(i.subject, signalMap[CONFLICT][d])
}

// Compensate emits the COMPENSATE signal.
// Indicates compensating action in saga pattern.
func (i *Transaction) Compensate(d Dimension) {
	i.percept.Emit(i.subject, signalMap[COMPENSATE][d])
}
