// Code generated by opphav-gen-symbols. DO NOT EDIT.

package leases

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "leases"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// ACQUIRE indicates a client is attempting to obtain a new lease.
	ACQUIRE = signs.Define("ACQUIRE")

	// DENY indicates a lease request has been denied.
	DENY = signs.Define("DENY")

	// EXTEND indicates the lease duration has been successfully extended.
	EXTEND = signs.Define("EXTEND")

	// EXPIRE indicates the lease has automatically terminated due to TTL exhaustion.
	EXPIRE = signs.Define("EXPIRE")

	// GRANT indicates the lease has been successfully granted.
	GRANT = signs.Define("GRANT")

	// PROBE indicates a status check is being performed on a lease.
	PROBE = signs.Define("PROBE")

	// RELEASE indicates the holder voluntarily terminated the lease before expiration.
	RELEASE = signs.Define("RELEASE")

	// RENEW indicates the holder is attempting to extend the lease duration.
	RENEW = signs.Define("RENEW")

	// REVOKE indicates the lease authority has forcefully revoked a lease.
	REVOKE = signs.Define("REVOKE")
)

var (
	// LESSOR The lease authority perspective.
	LESSOR = dimensions.Define("LESSOR")

	// LESSEE The lease client perspective.
	LESSEE = dimensions.Define("LESSEE")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		ACQUIRE: opphav.KindOperation,
		DENY:    opphav.KindOutcome,
		EXTEND:  opphav.KindOutcome,
		EXPIRE:  opphav.KindOutcome,
		GRANT:   opphav.KindOutcome,
		PROBE:   opphav.KindOperation,
		RELEASE: opphav.KindOperation,
		RENEW:   opphav.KindOperation,
		REVOKE:  opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Acquire returns the ACQUIRE signal for the given dimension.
// Indicates a client is attempting to obtain a new lease.
func Acquire(d Dimension) Signal {
	return signalMap[ACQUIRE][d].(Signal)
}

// Deny returns the DENY signal for the given dimension.
// Indicates a lease request has been denied.
func Deny(d Dimension) Signal {
	return signalMap[DENY][d].(Signal)
}

// Extend returns the EXTEND signal for the given dimension.
// Indicates the lease duration has been successfully extended.
func Extend(d Dimension) Signal {
	return signalMap[EXTEND][d].(Signal)
}

// Expire returns the EXPIRE signal for the given dimension.
// Indicates the lease has automatically terminated due to TTL exhaustion.
func Expire(d Dimension) Signal {
	return signalMap[EXPIRE][d].(Signal)
}

// Grant returns the GRANT signal for the given dimension.
// Indicates the lease has been successfully granted.
func Grant(d Dimension) Signal {
	return signalMap[GRANT][d].(Signal)
}

// Probe returns the PROBE signal for the given dimension.
// Indicates a status check is being performed on a lease.
func Probe(d Dimension) Signal {
	return signalMap[PROBE][d].(Signal)
}

// Release returns the RELEASE signal for the given dimension.
// Indicates the holder voluntarily terminated the lease before expiration.
func Release(d Dimension) Signal {
	return signalMap[RELEASE][d].(Signal)
}

// Renew returns the RENEW signal for the given dimension.
// Indicates the holder is attempting to extend the lease duration.
func Renew(d Dimension) Signal {
	return signalMap[RENEW][d].(Signal)
}

// Revoke returns the REVOKE signal for the given dimension.
// Indicates the lease authority has forcefully revoked a lease.
func Revoke(d Dimension) Signal {
	return signalMap[REVOKE][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Lease struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Lease {
	if percept == nil {
		panic("leases: percept must not be nil")
	}

	return &Lease{percept: percept, subject: subject}
}

// Acquire emits the ACQUIRE signal.
// Indicates a client is attempting to obtain a new lease.
func (i *Lease) Acquire(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ACQUIRE][d])
}

// Deny emits the DENY signal.
// Indicates a lease request has been denied.
func (i *Lease) Deny(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DENY][d])
}

// Extend emits the EXTEND signal.
// Indicates the lease duration has been successfully extended.
func (i *Lease) Extend(d Dimension) {
	i.percept.Emit(i.subject, signalMap[EXTEND][d])
}

// Expire emits the EXPIRE signal.
// Indicates the lease has automatically terminated due to TTL exhaustion.
func (i *Lease) Expire(d Dimension) {
	i.percept.Emit(i.subject, signalMap[EXPIRE][d])
}

// Grant emits the GRANT signal.
// Indicates the lease has been successfully granted.
func (i *Lease) Grant(d Dimension) {
	i.percept.Emit(i.subject, signalMap[GRANT][d])
}

// Probe emits the PROBE signal.
// Indicates a status check is being performed on a lease.
func (i *Lease) Probe(d Dimension) {
	i.percept.Emit(i.subject, signalMap[PROBE][d])
}

// Release emits the RELEASE signal.
// Indicates the holder voluntarily terminated the lease before expiration.
func (i *Lease) Release(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RELEASE][d])
}

// Renew emits the RENEW signal.
// Indicates the holder is attempting to extend the lease duration.
func (i *Lease) Renew(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RENEW][d])
}

// Revoke emits the REVOKE signal.
// Indicates the lease authority has forcefully revoked a lease.
func (i *Lease) Revoke(d Dimension) {
	i.percept.Emit(i.subject, signalMap[REVOKE][d])
}
