// Code generated by opphav-gen-symbols. DO NOT EDIT.

package breakers

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "breakers"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// CLOSE indicates the circuit is closed and operating normally.
	CLOSE = signs.Define("CLOSE")

	// OPEN indicates the circuit is open and blocking requests.
	OPEN = signs.Define("OPEN")

	// HALF_OPEN indicates the circuit is half-open and testing recovery.
	HALF_OPEN = signs.Define("HALF_OPEN")

	// TRIP indicates the failure threshold was exceeded, triggering circuit break.
	TRIP = signs.Define("TRIP")

	// PROBE indicates a test request is being sent in half-open state.
	PROBE = signs.Define("PROBE")

	// RESET indicates the circuit was manually reset to closed state.
	RESET = signs.Define("RESET")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		CLOSE:     opphav.KindOutcome,
		OPEN:      opphav.KindOutcome,
		HALF_OPEN: opphav.KindOutcome,
		TRIP:      opphav.KindOutcome,
		PROBE:     opphav.KindOperation,
		RESET:     opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Breaker struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Breaker {
	if percept == nil {
		panic("breakers: percept must not be nil")
	}

	return &Breaker{percept: percept, subject: subject}
}

// Close emits the CLOSE sign.
// Indicates the circuit is closed and operating normally.
func (i *Breaker) Close() {
	i.percept.Emit(i.subject, signMap[CLOSE])
}

// Open emits the OPEN sign.
// Indicates the circuit is open and blocking requests.
func (i *Breaker) Open() {
	i.percept.Emit(i.subject, signMap[OPEN])
}

// HalfOpen emits the HALF_OPEN sign.
// Indicates the circuit is half-open and testing recovery.
func (i *Breaker) HalfOpen() {
	i.percept.Emit(i.subject, signMap[HALF_OPEN])
}

// Trip emits the TRIP sign.
// Indicates the failure threshold was exceeded, triggering circuit break.
func (i *Breaker) Trip() {
	i.percept.Emit(i.subject, signMap[TRIP])
}

// Probe emits the PROBE sign.
// Indicates a test request is being sent in half-open state.
func (i *Breaker) Probe() {
	i.percept.Emit(i.subject, signMap[PROBE])
}

// Reset emits the RESET sign.
// Indicates the circuit was manually reset to closed state.
func (i *Breaker) Reset() {
	i.percept.Emit(i.subject, signMap[RESET])
}
