// Code generated by opphav-gen-symbols. DO NOT EDIT.

package operations

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "operations"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// BEGIN indicates an action is starting.
	BEGIN = signs.Define("BEGIN")

	// ADVANCE indicates an action is progressing within an open episode — neither beginning nor ending it.
	ADVANCE = signs.Define("ADVANCE")

	// END indicates an action is finishing.
	END = signs.Define("END")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Operation struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Operation {
	if percept == nil {
		panic("operations: percept must not be nil")
	}

	return &Operation{percept: percept, subject: subject}
}

// Begin emits the BEGIN sign.
// Indicates an action is starting.
func (i *Operation) Begin() {
	i.percept.Emit(i.subject, signMap[BEGIN])
}

// Advance emits the ADVANCE sign.
// Indicates an action is progressing within an open episode — neither beginning nor ending it.
func (i *Operation) Advance() {
	i.percept.Emit(i.subject, signMap[ADVANCE])
}

// End emits the END sign.
// Indicates an action is finishing.
func (i *Operation) End() {
	i.percept.Emit(i.subject, signMap[END])
}
