// Code generated by opphav-gen-symbols. DO NOT EDIT.

package agents

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "agents"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// OFFER indicates an agent is advertising a capability (promise available).
	OFFER = signs.Define("OFFER")

	// PROMISE indicates an agent is making a promise about its own behavior.
	PROMISE = signs.Define("PROMISE")

	// ACCEPT indicates an agent is accepting another agent's promise.
	ACCEPT = signs.Define("ACCEPT")

	// FULFILL indicates an agent kept its promise.
	FULFILL = signs.Define("FULFILL")

	// RETRACT indicates an agent is retracting a promise before fulfillment.
	RETRACT = signs.Define("RETRACT")

	// BREACH indicates an agent failed to keep its promise.
	BREACH = signs.Define("BREACH")

	// INQUIRE indicates an agent is asking about available capabilities.
	INQUIRE = signs.Define("INQUIRE")

	// OBSERVE indicates an agent is monitoring another agent's promise state.
	OBSERVE = signs.Define("OBSERVE")

	// DEPEND indicates an agent is declaring explicit dependency on a promise.
	DEPEND = signs.Define("DEPEND")

	// VALIDATE indicates an agent is confirming a promise is still held.
	VALIDATE = signs.Define("VALIDATE")
)

var (
	// PROMISER The emission of a promise signal from the agent's own perspective.
	PROMISER = dimensions.Define("PROMISER")

	// PROMISEE The reception of a promise signal from another agent's perspective.
	PROMISEE = dimensions.Define("PROMISEE")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		OFFER:    opphav.KindOperation,
		PROMISE:  opphav.KindOperation,
		ACCEPT:   opphav.KindOperation,
		FULFILL:  opphav.KindOutcome,
		RETRACT:  opphav.KindOperation,
		BREACH:   opphav.KindOutcome,
		INQUIRE:  opphav.KindOperation,
		OBSERVE:  opphav.KindOperation,
		DEPEND:   opphav.KindOperation,
		VALIDATE: opphav.KindOperation,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Offer returns the OFFER signal for the given dimension.
// Indicates an agent is advertising a capability (promise available).
func Offer(d Dimension) Signal {
	return signalMap[OFFER][d].(Signal)
}

// Promise returns the PROMISE signal for the given dimension.
// Indicates an agent is making a promise about its own behavior.
func Promise(d Dimension) Signal {
	return signalMap[PROMISE][d].(Signal)
}

// Accept returns the ACCEPT signal for the given dimension.
// Indicates an agent is accepting another agent's promise.
func Accept(d Dimension) Signal {
	return signalMap[ACCEPT][d].(Signal)
}

// Fulfill returns the FULFILL signal for the given dimension.
// Indicates an agent kept its promise.
func Fulfill(d Dimension) Signal {
	return signalMap[FULFILL][d].(Signal)
}

// Retract returns the RETRACT signal for the given dimension.
// Indicates an agent is retracting a promise before fulfillment.
func Retract(d Dimension) Signal {
	return signalMap[RETRACT][d].(Signal)
}

// Breach returns the BREACH signal for the given dimension.
// Indicates an agent failed to keep its promise.
func Breach(d Dimension) Signal {
	return signalMap[BREACH][d].(Signal)
}

// Inquire returns the INQUIRE signal for the given dimension.
// Indicates an agent is asking about available capabilities.
func Inquire(d Dimension) Signal {
	return signalMap[INQUIRE][d].(Signal)
}

// Observe returns the OBSERVE signal for the given dimension.
// Indicates an agent is monitoring another agent's promise state.
func Observe(d Dimension) Signal {
	return signalMap[OBSERVE][d].(Signal)
}

// Depend returns the DEPEND signal for the given dimension.
// Indicates an agent is declaring explicit dependency on a promise.
func Depend(d Dimension) Signal {
	return signalMap[DEPEND][d].(Signal)
}

// Validate returns the VALIDATE signal for the given dimension.
// Indicates an agent is confirming a promise is still held.
func Validate(d Dimension) Signal {
	return signalMap[VALIDATE][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Agent struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Agent {
	if percept == nil {
		panic("agents: percept must not be nil")
	}

	return &Agent{percept: percept, subject: subject}
}

// Offer emits the OFFER signal.
// Indicates an agent is advertising a capability (promise available).
func (i *Agent) Offer(d Dimension) {
	i.percept.Emit(i.subject, signalMap[OFFER][d])
}

// Promise emits the PROMISE signal.
// Indicates an agent is making a promise about its own behavior.
func (i *Agent) Promise(d Dimension) {
	i.percept.Emit(i.subject, signalMap[PROMISE][d])
}

// Accept emits the ACCEPT signal.
// Indicates an agent is accepting another agent's promise.
func (i *Agent) Accept(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ACCEPT][d])
}

// Fulfill emits the FULFILL signal.
// Indicates an agent kept its promise.
func (i *Agent) Fulfill(d Dimension) {
	i.percept.Emit(i.subject, signalMap[FULFILL][d])
}

// Retract emits the RETRACT signal.
// Indicates an agent is retracting a promise before fulfillment.
func (i *Agent) Retract(d Dimension) {
	i.percept.Emit(i.subject, signalMap[RETRACT][d])
}

// Breach emits the BREACH signal.
// Indicates an agent failed to keep its promise.
func (i *Agent) Breach(d Dimension) {
	i.percept.Emit(i.subject, signalMap[BREACH][d])
}

// Inquire emits the INQUIRE signal.
// Indicates an agent is asking about available capabilities.
func (i *Agent) Inquire(d Dimension) {
	i.percept.Emit(i.subject, signalMap[INQUIRE][d])
}

// Observe emits the OBSERVE signal.
// Indicates an agent is monitoring another agent's promise state.
func (i *Agent) Observe(d Dimension) {
	i.percept.Emit(i.subject, signalMap[OBSERVE][d])
}

// Depend emits the DEPEND signal.
// Indicates an agent is declaring explicit dependency on a promise.
func (i *Agent) Depend(d Dimension) {
	i.percept.Emit(i.subject, signalMap[DEPEND][d])
}

// Validate emits the VALIDATE signal.
// Indicates an agent is confirming a promise is still held.
func (i *Agent) Validate(d Dimension) {
	i.percept.Emit(i.subject, signalMap[VALIDATE][d])
}
