// Code generated by opphav-gen-symbols. DO NOT EDIT.

package timers

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "timers"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// MEET indicates the time constraint was satisfied.
	MEET = signs.Define("MEET")

	// MISS indicates the time constraint was violated.
	MISS = signs.Define("MISS")
)

var (
	// DEADLINE An absolute time constraint.
	DEADLINE = dimensions.Define("DEADLINE")

	// THRESHOLD A relative duration constraint.
	THRESHOLD = dimensions.Define("THRESHOLD")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}

	kindMap = map[Sign]opphav.Kind{
		MEET: opphav.KindOutcome,
		MISS: opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

// Meet returns the MEET signal for the given dimension.
// Indicates the time constraint was satisfied.
func Meet(d Dimension) Signal {
	return signalMap[MEET][d].(Signal)
}

// Miss returns the MISS signal for the given dimension.
// Indicates the time constraint was violated.
func Miss(d Dimension) Signal {
	return signalMap[MISS][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Timer struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Timer {
	if percept == nil {
		panic("timers: percept must not be nil")
	}

	return &Timer{percept: percept, subject: subject}
}

// Meet emits the MEET signal.
// Indicates the time constraint was satisfied.
func (i *Timer) Meet(d Dimension) {
	i.percept.Emit(i.subject, signalMap[MEET][d])
}

// Miss emits the MISS signal.
// Indicates the time constraint was violated.
func (i *Timer) Miss(d Dimension) {
	i.percept.Emit(i.subject, signalMap[MISS][d])
}
