// Code generated by opphav-gen-symbols. DO NOT EDIT.

package locks

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "locks"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// ATTEMPT indicates a non-blocking lock acquisition attempt (try-lock).
	ATTEMPT = signs.Define("ATTEMPT")

	// ACQUIRE indicates a blocking lock acquisition request (willing to wait).
	ACQUIRE = signs.Define("ACQUIRE")

	// GRANT indicates lock successfully obtained.
	GRANT = signs.Define("GRANT")

	// DENY indicates non-blocking acquisition denied (try-lock failed).
	DENY = signs.Define("DENY")

	// TIMEOUT indicates blocking acquisition exceeded time limit.
	TIMEOUT = signs.Define("TIMEOUT")

	// RELEASE indicates lock voluntarily released by holder.
	RELEASE = signs.Define("RELEASE")

	// UPGRADE indicates read lock upgraded to write lock (RW locks).
	UPGRADE = signs.Define("UPGRADE")

	// DOWNGRADE indicates write lock downgraded to read lock (RW locks).
	DOWNGRADE = signs.Define("DOWNGRADE")

	// CONTEST indicates CAS failure or contention detected.
	CONTEST = signs.Define("CONTEST")

	// ABANDON indicates lock holder terminated without releasing.
	ABANDON = signs.Define("ABANDON")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		ATTEMPT:   opphav.KindOperation,
		ACQUIRE:   opphav.KindOperation,
		GRANT:     opphav.KindOutcome,
		DENY:      opphav.KindOutcome,
		TIMEOUT:   opphav.KindOutcome,
		RELEASE:   opphav.KindOperation,
		UPGRADE:   opphav.KindOperation,
		DOWNGRADE: opphav.KindOperation,
		CONTEST:   opphav.KindOutcome,
		ABANDON:   opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Lock struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Lock {
	if percept == nil {
		panic("locks: percept must not be nil")
	}

	return &Lock{percept: percept, subject: subject}
}

// Attempt emits the ATTEMPT sign.
// Indicates a non-blocking lock acquisition attempt (try-lock).
func (i *Lock) Attempt() {
	i.percept.Emit(i.subject, signMap[ATTEMPT])
}

// Acquire emits the ACQUIRE sign.
// Indicates a blocking lock acquisition request (willing to wait).
func (i *Lock) Acquire() {
	i.percept.Emit(i.subject, signMap[ACQUIRE])
}

// Grant emits the GRANT sign.
// Indicates lock successfully obtained.
func (i *Lock) Grant() {
	i.percept.Emit(i.subject, signMap[GRANT])
}

// Deny emits the DENY sign.
// Indicates non-blocking acquisition denied (try-lock failed).
func (i *Lock) Deny() {
	i.percept.Emit(i.subject, signMap[DENY])
}

// Timeout emits the TIMEOUT sign.
// Indicates blocking acquisition exceeded time limit.
func (i *Lock) Timeout() {
	i.percept.Emit(i.subject, signMap[TIMEOUT])
}

// Release emits the RELEASE sign.
// Indicates lock voluntarily released by holder.
func (i *Lock) Release() {
	i.percept.Emit(i.subject, signMap[RELEASE])
}

// Upgrade emits the UPGRADE sign.
// Indicates read lock upgraded to write lock (RW locks).
func (i *Lock) Upgrade() {
	i.percept.Emit(i.subject, signMap[UPGRADE])
}

// Downgrade emits the DOWNGRADE sign.
// Indicates write lock downgraded to read lock (RW locks).
func (i *Lock) Downgrade() {
	i.percept.Emit(i.subject, signMap[DOWNGRADE])
}

// Contest emits the CONTEST sign.
// Indicates CAS failure or contention detected.
func (i *Lock) Contest() {
	i.percept.Emit(i.subject, signMap[CONTEST])
}

// Abandon emits the ABANDON sign.
// Indicates lock holder terminated without releasing.
func (i *Lock) Abandon() {
	i.percept.Emit(i.subject, signMap[ABANDON])
}
