// Code generated by opphav-gen-symbols. DO NOT EDIT.

package systems

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "systems"

type Sign struct {
	opphav.SignEntry
}

type Dimension struct {
	opphav.CategoryEntry
}

type Signal = opphav.Signal[Sign, Dimension]

var (
	signs = opphav.NewSignSet(
		domain,
		func(e opphav.SignEntry) Sign {
			return Sign{e}
		},
	)

	dimensions = opphav.NewCategorySet(
		domain,
		func(e opphav.CategoryEntry) Dimension {
			return Dimension{e}
		},
	)
)

var (
	// NORMAL Operating within standard parameters.
	NORMAL = signs.Define("NORMAL")

	// LIMIT At constraint boundary.
	LIMIT = signs.Define("LIMIT")

	// ALARM Beyond constraint boundary.
	ALARM = signs.Define("ALARM")

	// FAULT Constraint failed.
	FAULT = signs.Define("FAULT")
)

var (
	// SPACE Container constraint — capacity, volume, room.
	SPACE = dimensions.Define("SPACE")

	// FLOW Movement constraint — throughput, bandwidth, rate.
	FLOW = dimensions.Define("FLOW")

	// LINK Structural constraint — connectivity, reachability, edges.
	LINK = dimensions.Define("LINK")

	// TIME Temporal constraint — latency, responsiveness, duration.
	TIME = dimensions.Define("TIME")
)

var signalMap map[Sign]map[Dimension]opphav.Observable

func init() {
	signalMap = make(map[Sign]map[Dimension]opphav.Observable)
	for _, s := range Signs() {
		signalMap[s] = make(map[Dimension]opphav.Observable)
		for _, d := range Dimensions() {
			signalMap[s][d] = opphav.NewSignal(s, d)
		}
	}
}

// Normal returns the NORMAL signal for the given dimension.
// Operating within standard parameters.
func Normal(d Dimension) Signal {
	return signalMap[NORMAL][d].(Signal)
}

// Limit returns the LIMIT signal for the given dimension.
// At constraint boundary.
func Limit(d Dimension) Signal {
	return signalMap[LIMIT][d].(Signal)
}

// Alarm returns the ALARM signal for the given dimension.
// Beyond constraint boundary.
func Alarm(d Dimension) Signal {
	return signalMap[ALARM][d].(Signal)
}

// Fault returns the FAULT signal for the given dimension.
// Constraint failed.
func Fault(d Dimension) Signal {
	return signalMap[FAULT][d].(Signal)
}

func NewSignal(sign Sign, dimension Dimension) Signal {
	return signalMap[sign][dimension].(Signal)
}

func Signs() []Sign {
	return signs.Members()
}

func Dimensions() []Dimension {
	return dimensions.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func LookupDimension(qualified string) (Dimension, bool) {
	return dimensions.Lookup(qualified)
}

type System struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *System {
	if percept == nil {
		panic("systems: percept must not be nil")
	}

	return &System{percept: percept, subject: subject}
}

// Normal emits the NORMAL signal.
// Operating within standard parameters.
func (i *System) Normal(d Dimension) {
	i.percept.Emit(i.subject, signalMap[NORMAL][d])
}

// Limit emits the LIMIT signal.
// At constraint boundary.
func (i *System) Limit(d Dimension) {
	i.percept.Emit(i.subject, signalMap[LIMIT][d])
}

// Alarm emits the ALARM signal.
// Beyond constraint boundary.
func (i *System) Alarm(d Dimension) {
	i.percept.Emit(i.subject, signalMap[ALARM][d])
}

// Fault emits the FAULT signal.
// Constraint failed.
func (i *System) Fault(d Dimension) {
	i.percept.Emit(i.subject, signalMap[FAULT][d])
}
