// Code generated by opphav-gen-symbols. DO NOT EDIT.

package queues

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "queues"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// ENQUEUE indicates an item was successfully added to the queue.
	ENQUEUE = signs.Define("ENQUEUE")

	// DEQUEUE indicates an item was successfully removed from the queue.
	DEQUEUE = signs.Define("DEQUEUE")

	// OVERFLOW indicates the queue reached capacity and rejected an ENQUEUE operation.
	OVERFLOW = signs.Define("OVERFLOW")

	// UNDERFLOW indicates the queue was empty and could not satisfy a DEQUEUE operation.
	UNDERFLOW = signs.Define("UNDERFLOW")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Queue struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Queue {
	if percept == nil {
		panic("queues: percept must not be nil")
	}

	return &Queue{percept: percept, subject: subject}
}

// Enqueue emits the ENQUEUE sign.
// Indicates an item was successfully added to the queue.
func (i *Queue) Enqueue() {
	i.percept.Emit(i.subject, signMap[ENQUEUE])
}

// Dequeue emits the DEQUEUE sign.
// Indicates an item was successfully removed from the queue.
func (i *Queue) Dequeue() {
	i.percept.Emit(i.subject, signMap[DEQUEUE])
}

// Overflow emits the OVERFLOW sign.
// Indicates the queue reached capacity and rejected an ENQUEUE operation.
func (i *Queue) Overflow() {
	i.percept.Emit(i.subject, signMap[OVERFLOW])
}

// Underflow emits the UNDERFLOW sign.
// Indicates the queue was empty and could not satisfy a DEQUEUE operation.
func (i *Queue) Underflow() {
	i.percept.Emit(i.subject, signMap[UNDERFLOW])
}
