// Code generated by opphav-gen-symbols. DO NOT EDIT.

package routers

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "routers"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// SEND A packet was transmitted from this router.
	SEND = signs.Define("SEND")

	// RECEIVE A packet was received by this router.
	RECEIVE = signs.Define("RECEIVE")

	// FORWARD A packet was forwarded to the next hop.
	FORWARD = signs.Define("FORWARD")

	// ROUTE A routing decision was made for a packet.
	ROUTE = signs.Define("ROUTE")

	// DROP A packet was discarded.
	DROP = signs.Define("DROP")

	// FRAGMENT A packet was fragmented due to MTU constraints.
	FRAGMENT = signs.Define("FRAGMENT")

	// REASSEMBLE Packet fragments were reassembled.
	REASSEMBLE = signs.Define("REASSEMBLE")

	// CORRUPT Packet corruption was detected.
	CORRUPT = signs.Define("CORRUPT")

	// REORDER Out-of-order packet arrival was detected.
	REORDER = signs.Define("REORDER")
)

var signMap map[Sign]opphav.Observable

var (
	kindMap map[Sign]opphav.Kind
)

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}

	kindMap = map[Sign]opphav.Kind{
		SEND:       opphav.KindOperation,
		RECEIVE:    opphav.KindOperation,
		FORWARD:    opphav.KindOperation,
		ROUTE:      opphav.KindOperation,
		DROP:       opphav.KindOperation,
		FRAGMENT:   opphav.KindOperation,
		REASSEMBLE: opphav.KindOperation,
		CORRUPT:    opphav.KindOutcome,
		REORDER:    opphav.KindOutcome,
	}

	for _, sign := range Signs() {
		if _, ok := kindMap[sign]; !ok {
			panic(domain + ": no kind classified for " + sign.Name())
		}
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

func Kind(sign Sign) (opphav.Kind, bool) {
	kind, ok := kindMap[sign]
	return kind, ok
}

type Router struct {
	percept *opphav.Percept
	subject opphav.Subject
}

func New(percept *opphav.Percept, subject opphav.Subject) *Router {
	if percept == nil {
		panic("routers: percept must not be nil")
	}

	return &Router{percept: percept, subject: subject}
}

// Send emits the SEND sign.
// A packet was transmitted from this router.
func (i *Router) Send() {
	i.percept.Emit(i.subject, signMap[SEND])
}

// Receive emits the RECEIVE sign.
// A packet was received by this router.
func (i *Router) Receive() {
	i.percept.Emit(i.subject, signMap[RECEIVE])
}

// Forward emits the FORWARD sign.
// A packet was forwarded to the next hop.
func (i *Router) Forward() {
	i.percept.Emit(i.subject, signMap[FORWARD])
}

// Route emits the ROUTE sign.
// A routing decision was made for a packet.
func (i *Router) Route() {
	i.percept.Emit(i.subject, signMap[ROUTE])
}

// Drop emits the DROP sign.
// A packet was discarded.
func (i *Router) Drop() {
	i.percept.Emit(i.subject, signMap[DROP])
}

// Fragment emits the FRAGMENT sign.
// A packet was fragmented due to MTU constraints.
func (i *Router) Fragment() {
	i.percept.Emit(i.subject, signMap[FRAGMENT])
}

// Reassemble emits the REASSEMBLE sign.
// Packet fragments were reassembled.
func (i *Router) Reassemble() {
	i.percept.Emit(i.subject, signMap[REASSEMBLE])
}

// Corrupt emits the CORRUPT sign.
// Packet corruption was detected.
func (i *Router) Corrupt() {
	i.percept.Emit(i.subject, signMap[CORRUPT])
}

// Reorder emits the REORDER sign.
// Out-of-order packet arrival was detected.
func (i *Router) Reorder() {
	i.percept.Emit(i.subject, signMap[REORDER])
}
