// Code generated by opphav-gen-symbols. DO NOT EDIT.

package pipelines

import (
	"opphav.io/sdk-go/opphav"
)

const domain = "pipelines"

type Sign struct {
	opphav.SignEntry
}

var signs = opphav.NewSignSet(
	domain,
	func(e opphav.SignEntry) Sign {
		return Sign{e}
	},
)

var (
	// INPUT Data was received from upstream stage.
	INPUT = signs.Define("INPUT")

	// OUTPUT Data was sent to downstream stage.
	OUTPUT = signs.Define("OUTPUT")

	// TRANSFORM Data was transformed.
	TRANSFORM = signs.Define("TRANSFORM")

	// FILTER Data was filtered out.
	FILTER = signs.Define("FILTER")

	// AGGREGATE Data was aggregated.
	AGGREGATE = signs.Define("AGGREGATE")

	// BUFFER Data was buffered.
	BUFFER = signs.Define("BUFFER")

	// BACKPRESSURE Backpressure was applied.
	BACKPRESSURE = signs.Define("BACKPRESSURE")

	// OVERFLOW Buffer overflow occurred.
	OVERFLOW = signs.Define("OVERFLOW")

	// CHECKPOINT Processing checkpoint reached.
	CHECKPOINT = signs.Define("CHECKPOINT")

	// WATERMARK Event-time watermark advanced.
	WATERMARK = signs.Define("WATERMARK")

	// LAG Processing lag detected.
	LAG = signs.Define("LAG")

	// SKIP Data was skipped or dropped.
	SKIP = signs.Define("SKIP")
)

var signMap map[Sign]opphav.Observable

func init() {
	signMap = make(map[Sign]opphav.Observable)
	for _, s := range Signs() {
		signMap[s] = s
	}
}

func Signs() []Sign {
	return signs.Members()
}

func LookupSign(qualified string) (Sign, bool) {
	return signs.Lookup(qualified)
}

type Pipeline struct {
	percept *opphav.Percept
	subject opphav.Name
}

func New(percept *opphav.Percept, subject opphav.Name) *Pipeline {
	if percept == nil {
		panic("pipelines: percept must not be nil")
	}

	return &Pipeline{percept: percept, subject: subject}
}

// Input emits the INPUT sign.
// Data was received from upstream stage.
func (i *Pipeline) Input() {
	i.percept.Emit(i.subject, signMap[INPUT])
}

// Output emits the OUTPUT sign.
// Data was sent to downstream stage.
func (i *Pipeline) Output() {
	i.percept.Emit(i.subject, signMap[OUTPUT])
}

// Transform emits the TRANSFORM sign.
// Data was transformed.
func (i *Pipeline) Transform() {
	i.percept.Emit(i.subject, signMap[TRANSFORM])
}

// Filter emits the FILTER sign.
// Data was filtered out.
func (i *Pipeline) Filter() {
	i.percept.Emit(i.subject, signMap[FILTER])
}

// Aggregate emits the AGGREGATE sign.
// Data was aggregated.
func (i *Pipeline) Aggregate() {
	i.percept.Emit(i.subject, signMap[AGGREGATE])
}

// Buffer emits the BUFFER sign.
// Data was buffered.
func (i *Pipeline) Buffer() {
	i.percept.Emit(i.subject, signMap[BUFFER])
}

// Backpressure emits the BACKPRESSURE sign.
// Backpressure was applied.
func (i *Pipeline) Backpressure() {
	i.percept.Emit(i.subject, signMap[BACKPRESSURE])
}

// Overflow emits the OVERFLOW sign.
// Buffer overflow occurred.
func (i *Pipeline) Overflow() {
	i.percept.Emit(i.subject, signMap[OVERFLOW])
}

// Checkpoint emits the CHECKPOINT sign.
// Processing checkpoint reached.
func (i *Pipeline) Checkpoint() {
	i.percept.Emit(i.subject, signMap[CHECKPOINT])
}

// Watermark emits the WATERMARK sign.
// Event-time watermark advanced.
func (i *Pipeline) Watermark() {
	i.percept.Emit(i.subject, signMap[WATERMARK])
}

// Lag emits the LAG sign.
// Processing lag detected.
func (i *Pipeline) Lag() {
	i.percept.Emit(i.subject, signMap[LAG])
}

// Skip emits the SKIP sign.
// Data was skipped or dropped.
func (i *Pipeline) Skip() {
	i.percept.Emit(i.subject, signMap[SKIP])
}
